kind: Service
apiVersion: v1
metadata:
  name: gohello-service
spec:
  selector:
    app: gohello
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-gohello
  labels:
    app: gohello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohello
  template:
    metadata:
      labels:
        app: gohello
    spec:
      imagePullSecrets:
      - name: hub
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8081
